server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    me.bvn13.openfeign.logger.NormalizedFeignLogger: DEBUG

spring:
  application:
    name: flxpoint_test

integrations:
  crm:
    base-url: http://crm:3000/customers